name = "income-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
# route = "income.do/api/*"
main = "worker.js"
compatibility_date = "2022-08-04"

[durable_objects]
bindings = [{name = "INCOME", class_name = "Income"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Income"]
